add promise tasks without 6 7
dariapatskevich/js-pro-course pull request #2
Opened 2021-08-29 18:04 UTC by dariapatskevich

сто-то получилось, сто-то нет😤

2021-08-29 18:06 UTC, dariapatskevich commented
забыла убрать txt файл, не сердись :)

2021-08-30 12:20 UTC, dromanchuck requested changes

2021-08-30 12:20 UTC, dromanchuck commented on lecture-2/index.txt
> +1
файлы расширения txt не нужны, можешь его удалить

2021-08-30 12:20 UTC, dromanchuck commented on lecture-2/main.js
> +    );
для того, чтобы посмотреть что будет в реджекте надо использовать catch
```js
promise.catch(error => document.write(error));

2021-08-30 12:20 UTC, dromanchuck commented on lecture-2/main.js
> +let promise = new Promise((reject) => {
при создании промиса коллбэк принимает 2 аргумента
let promise = new Promise((resolve, reject) => {
а у тебя let promise = new Promise((reject) => {
при такой записи фактически ты назвала функцию  resolve -> reject
и поэтому then ниже сработал

Не забывай коллбэк при создании промиса имеет 2 аргумента resolve и reject

2021-08-30 12:20 UTC, dromanchuck commented on lecture-2/main.js
> +Promise.all(arr.map(sumOfArrays)).then(results => console.log(results));
посмотри здесь https://learn.javascript.ru/promise-api#promise-all

Promise.all принимает массив из промисов, т.е тут надо было так сделать
let resultPromise = Promise.all([promise1, promise2, promise3])
и потом уже в этом результирующем промисе использовать then и там результатом будет массив, который собирается из резолвов промисов массива
resultPromise.then(arr => console.log(arr)) /// [1,2,3]

2021-09-04 12:32 UTC, closed without merging